import { db } from '@/db';
import { marks } from '@/db/schema';

async function main() {
    const sampleMarks = [
        // Student 1 - Mathematics (Subject 1)
        {
            studentId: 1,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 87,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 1,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 92,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 1 - English (Subject 2)
        {
            studentId: 1,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 78,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 1,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 85,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 1 - Science (Subject 3)
        {
            studentId: 1,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 90,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 1,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 88,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 1 - Social Studies (Subject 4)
        {
            studentId: 1,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 82,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 1,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 79,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },

        // Student 2 - Mathematics (Subject 1)
        {
            studentId: 2,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 75,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 2,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 81,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 2 - English (Subject 2)
        {
            studentId: 2,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 88,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 2,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 91,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 2 - Science (Subject 3)
        {
            studentId: 2,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 72,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 2,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 77,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 2 - Social Studies (Subject 4)
        {
            studentId: 2,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 85,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 2,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 83,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },

        // Student 3 - Mathematics (Subject 1)
        {
            studentId: 3,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 94,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 3,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 96,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 3 - English (Subject 2)
        {
            studentId: 3,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 89,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 3,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 92,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 3 - Science (Subject 3)
        {
            studentId: 3,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 91,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 3,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 95,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 3 - Social Studies (Subject 4)
        {
            studentId: 3,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 88,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 3,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 90,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },

        // Student 4 - Mathematics (Subject 1)
        {
            studentId: 4,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 68,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Needs Improvement',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 4,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 74,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 4 - English (Subject 2)
        {
            studentId: 4,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 76,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 4,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 80,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 4 - Science (Subject 3)
        {
            studentId: 4,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 70,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 4,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 72,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 4 - Social Studies (Subject 4)
        {
            studentId: 4,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 81,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 4,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 78,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },

        // Student 5 - Mathematics (Subject 1)
        {
            studentId: 5,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 0,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Absent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 5,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 85,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 5 - English (Subject 2)
        {
            studentId: 5,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 82,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 5,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 87,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 5 - Science (Subject 3)
        {
            studentId: 5,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 79,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 5,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 83,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 5 - Social Studies (Subject 4)
        {
            studentId: 5,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 77,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 5,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 80,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },

        // Student 6 - Mathematics (Subject 1)
        {
            studentId: 6,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 91,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 6,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 89,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 6 - English (Subject 2)
        {
            studentId: 6,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 84,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 6,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 86,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 6 - Science (Subject 3)
        {
            studentId: 6,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 88,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 6,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 92,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 6 - Social Studies (Subject 4)
        {
            studentId: 6,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 80,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 6,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 84,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },

        // Student 7 - Mathematics (Subject 1)
        {
            studentId: 7,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 73,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 7,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 79,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 7 - English (Subject 2)
        {
            studentId: 7,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 86,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 7,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 90,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 7 - Science (Subject 3)
        {
            studentId: 7,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 75,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 7,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 81,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 7 - Social Studies (Subject 4)
        {
            studentId: 7,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 78,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 7,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 76,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },

        // Student 8 - Mathematics (Subject 1)
        {
            studentId: 8,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 65,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Needs Improvement',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 8,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 71,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 8 - English (Subject 2)
        {
            studentId: 8,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 74,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 8,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 78,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 8 - Science (Subject 3)
        {
            studentId: 8,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 68,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Needs Improvement',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 8,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 73,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 8 - Social Studies (Subject 4)
        {
            studentId: 8,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 72,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 8,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 75,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },

        // Student 9 - Mathematics (Subject 1)
        {
            studentId: 9,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 89,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 9,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 93,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 9 - English (Subject 2)
        {
            studentId: 9,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 85,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 9,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 88,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 9 - Science (Subject 3)
        {
            studentId: 9,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 92,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 9,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 94,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        // Student 9 - Social Studies (Subject 4)
        {
            studentId: 9,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 87,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 9,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 91,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Excellent',
            createdAt: new Date().toISOString(),
        },

        // Student 10 - Mathematics (Subject 1)
        {
            studentId: 10,
            subjectId: 1,
            examType: 'Unit Test 1',
            marksObtained: 76,
            totalMarks: 100,
            examDate: new Date('2024-08-15').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 10,
            subjectId: 1,
            examType: 'Midterm',
            marksObtained: 82,
            totalMarks: 100,
            examDate: new Date('2024-10-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 10 - English (Subject 2)
        {
            studentId: 10,
            subjectId: 2,
            examType: 'Unit Test 1',
            marksObtained: 81,
            totalMarks: 100,
            examDate: new Date('2024-08-18').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 10,
            subjectId: 2,
            examType: 'Midterm',
            marksObtained: 84,
            totalMarks: 100,
            examDate: new Date('2024-10-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 10 - Science (Subject 3)
        {
            studentId: 10,
            subjectId: 3,
            examType: 'Unit Test 1',
            marksObtained: 77,
            totalMarks: 100,
            examDate: new Date('2024-08-20').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 10,
            subjectId: 3,
            examType: 'Midterm',
            marksObtained: 80,
            totalMarks: 100,
            examDate: new Date('2024-10-24').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        // Student 10 - Social Studies (Subject 4)
        {
            studentId: 10,
            subjectId: 4,
            examType: 'Unit Test 1',
            marksObtained: 79,
            totalMarks: 100,
            examDate: new Date('2024-08-22').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
        {
            studentId: 10,
            subjectId: 4,
            examType: 'Midterm',
            marksObtained: 83,
            totalMarks: 100,
            examDate: new Date('2024-10-26').toISOString(),
            remarks: 'Good',
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(marks).values(sampleMarks);
    
    console.log('✅ Marks seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});