import { db } from '@/db';
import { notifications } from '@/db/schema';

async function main() {
    const sampleNotifications = [
        {
            recipientId: 1,
            title: 'Low Attendance Alert',
            message: 'Your attendance has fallen below 75%. Please ensure regular attendance to avoid academic issues.',
            type: 'attendance',
            isRead: false,
            sentViaWhatsapp: true,
            createdAt: new Date('2024-01-15T09:00:00').toISOString(),
        },
        {
            recipientId: 2,
            title: 'Fee Payment Due',
            message: 'Your quarterly fee payment of ₹15,000 is due on January 31st, 2024. Please make the payment to avoid late fees.',
            type: 'fee',
            isRead: false,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-16T10:30:00').toISOString(),
        },
        {
            recipientId: 3,
            title: 'Exam Schedule Released',
            message: 'The first semester examination schedule has been released. Please check the student portal for detailed timings.',
            type: 'academic',
            isRead: true,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-17T11:15:00').toISOString(),
        },
        {
            recipientId: 4,
            title: 'Your Child Was Absent Today',
            message: 'Your child Rahul Kumar was marked absent on January 18th, 2024. If this is incorrect, please contact the class teacher.',
            type: 'attendance',
            isRead: false,
            sentViaWhatsapp: true,
            createdAt: new Date('2024-01-18T14:45:00').toISOString(),
        },
        {
            recipientId: 5,
            title: 'Fee Payment Received',
            message: 'Thank you! Your fee payment of ₹12,000 has been successfully received. Receipt number: FEE2024001.',
            type: 'fee',
            isRead: true,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-19T09:20:00').toISOString(),
        },
        {
            recipientId: 6,
            title: 'Result Published',
            message: 'Your semester results have been published. You scored 85% overall. Login to view detailed marks.',
            type: 'academic',
            isRead: false,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-20T10:00:00').toISOString(),
        },
        {
            recipientId: 7,
            title: 'Attendance Warning',
            message: 'Your child has been absent for 3 consecutive days. Please provide a medical certificate or contact the school office.',
            type: 'attendance',
            isRead: false,
            sentViaWhatsapp: true,
            createdAt: new Date('2024-01-21T08:30:00').toISOString(),
        },
        {
            recipientId: 8,
            title: 'Fee Payment Overdue',
            message: 'Your fee payment is overdue by 15 days. Late fee of ₹500 has been added. Total due: ₹15,500.',
            type: 'fee',
            isRead: true,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-22T11:45:00').toISOString(),
        },
        {
            recipientId: 9,
            title: 'Parent-Teacher Meeting',
            message: 'Parent-Teacher meeting scheduled for February 5th, 2024 at 10:00 AM. Your presence is mandatory.',
            type: 'general',
            isRead: false,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-23T09:15:00').toISOString(),
        },
        {
            recipientId: 10,
            title: 'Assignment Submission Due',
            message: 'Mathematics assignment submission deadline is January 30th, 2024. Late submissions will not be accepted.',
            type: 'academic',
            isRead: false,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-24T10:30:00').toISOString(),
        },
        {
            recipientId: 1,
            title: 'Perfect Attendance Award',
            message: 'Congratulations! You have maintained 100% attendance this month. Keep up the excellent work!',
            type: 'attendance',
            isRead: true,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-25T12:00:00').toISOString(),
        },
        {
            recipientId: 2,
            title: 'Fee Installment Plan Available',
            message: 'Fee installment plan is now available. You can pay in 3 easy installments. Contact admin for details.',
            type: 'fee',
            isRead: false,
            sentViaWhatsapp: true,
            createdAt: new Date('2024-01-26T09:45:00').toISOString(),
        },
        {
            recipientId: 3,
            title: 'Science Fair Registration Open',
            message: 'Annual Science Fair registration is now open. Register before February 10th to participate.',
            type: 'academic',
            isRead: true,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-27T11:20:00').toISOString(),
        },
        {
            recipientId: 4,
            title: 'Late Arrival Notice',
            message: 'Your child arrived late to school today at 9:15 AM. Please ensure timely arrival to avoid missing classes.',
            type: 'attendance',
            isRead: false,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-28T09:30:00').toISOString(),
        },
        {
            recipientId: 5,
            title: 'Fee Discount Available',
            message: 'Early bird discount of 10% available on next quarter fees if paid before February 15th, 2024.',
            type: 'fee',
            isRead: false,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-29T10:15:00').toISOString(),
        },
        {
            recipientId: 6,
            title: 'Class Test Announcement',
            message: 'Class test in Mathematics scheduled for February 2nd, 2024. Topics: Algebra and Geometry.',
            type: 'academic',
            isRead: true,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-30T08:45:00').toISOString(),
        },
        {
            recipientId: 7,
            title: 'Half Day Attendance',
            message: 'Your child was marked as half-day present today due to early departure at 11:30 AM for medical reasons.',
            type: 'attendance',
            isRead: true,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-01-31T14:00:00').toISOString(),
        },
        {
            recipientId: 8,
            title: 'Scholarship Application Open',
            message: 'Merit-based scholarship applications are now open. Submit your application before February 20th, 2024.',
            type: 'fee',
            isRead: false,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-02-01T09:00:00').toISOString(),
        },
        {
            recipientId: 9,
            title: 'School Holiday Notice',
            message: 'School will remain closed on February 15th, 2024 on account of public holiday. Classes will resume on February 16th.',
            type: 'general',
            isRead: false,
            sentViaWhatsapp: true,
            createdAt: new Date('2024-02-02T10:30:00').toISOString(),
        },
        {
            recipientId: 10,
            title: 'Annual Sports Day Registration',
            message: 'Annual Sports Day is scheduled for March 15th, 2024. Register for your preferred events before February 28th.',
            type: 'academic',
            isRead: false,
            sentViaWhatsapp: false,
            createdAt: new Date('2024-02-03T11:45:00').toISOString(),
        },
    ];

    await db.insert(notifications).values(sampleNotifications);
    
    console.log('✅ Notifications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});