import { db } from '@/db';
import { students } from '@/db/schema';

async function main() {
    const sampleStudents = [
        // Section 1 (Class 8A) - Students 1-5
        {
            userId: 7,
            admissionNumber: 'ADM001',
            rollNumber: '1',
            sectionId: 1,
            dateOfBirth: '2010-03-15',
            gender: 'Male',
            bloodGroup: 'A+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student001',
            password: 'student123',
            studentMobileNumber: '+9876543211',
            parentName: 'Mr. Rajesh Kumar',
            parentMobileNumber: '+9876543212',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 8,
            admissionNumber: 'ADM002',
            rollNumber: '2',
            sectionId: 1,
            dateOfBirth: '2010-05-20',
            gender: 'Female',
            bloodGroup: 'B+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student002',
            password: 'student123',
            studentMobileNumber: '+9876543213',
            parentName: 'Mrs. Priya Sharma',
            parentMobileNumber: '+9876543214',
            feesConcession: 10,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 9,
            admissionNumber: 'ADM003',
            rollNumber: '3',
            sectionId: 1,
            dateOfBirth: '2010-07-10',
            gender: 'Male',
            bloodGroup: 'O+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student003',
            password: 'student123',
            studentMobileNumber: '+9876543215',
            parentName: 'Mr. Amit Patel',
            parentMobileNumber: '+9876543216',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 10,
            admissionNumber: 'ADM004',
            rollNumber: '4',
            sectionId: 1,
            dateOfBirth: '2010-09-25',
            gender: 'Female',
            bloodGroup: 'AB+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student004',
            password: 'student123',
            studentMobileNumber: '+9876543217',
            parentName: 'Mrs. Sunita Gupta',
            parentMobileNumber: '+9876543218',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 11,
            admissionNumber: 'ADM005',
            rollNumber: '5',
            sectionId: 1,
            dateOfBirth: '2010-11-12',
            gender: 'Male',
            bloodGroup: 'A+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student005',
            password: 'student123',
            studentMobileNumber: '+9876543219',
            parentName: 'Mr. Vikram Singh',
            parentMobileNumber: '+9876543220',
            feesConcession: 15,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        // Section 2 (Class 8B) - Students 6-10
        {
            userId: 12,
            admissionNumber: 'ADM006',
            rollNumber: '1',
            sectionId: 2,
            dateOfBirth: '2010-02-18',
            gender: 'Female',
            bloodGroup: 'B+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student006',
            password: 'student123',
            studentMobileNumber: '+9876543221',
            parentName: 'Mrs. Kavita Verma',
            parentMobileNumber: '+9876543222',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 13,
            admissionNumber: 'ADM007',
            rollNumber: '2',
            sectionId: 2,
            dateOfBirth: '2010-04-22',
            gender: 'Male',
            bloodGroup: 'O+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student007',
            password: 'student123',
            studentMobileNumber: '+9876543223',
            parentName: 'Mr. Suresh Reddy',
            parentMobileNumber: '+9876543224',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 14,
            admissionNumber: 'ADM008',
            rollNumber: '3',
            sectionId: 2,
            dateOfBirth: '2010-06-30',
            gender: 'Female',
            bloodGroup: 'AB+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student008',
            password: 'student123',
            studentMobileNumber: '+9876543225',
            parentName: 'Mrs. Neha Joshi',
            parentMobileNumber: '+9876543226',
            feesConcession: 5,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 15,
            admissionNumber: 'ADM009',
            rollNumber: '4',
            sectionId: 2,
            dateOfBirth: '2010-08-14',
            gender: 'Male',
            bloodGroup: 'A+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student009',
            password: 'student123',
            studentMobileNumber: '+9876543227',
            parentName: 'Mr. Rahul Mehta',
            parentMobileNumber: '+9876543228',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 16,
            admissionNumber: 'ADM010',
            rollNumber: '5',
            sectionId: 2,
            dateOfBirth: '2010-10-05',
            gender: 'Female',
            bloodGroup: 'B+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student010',
            password: 'student123',
            studentMobileNumber: '+9876543229',
            parentName: 'Mrs. Pooja Agarwal',
            parentMobileNumber: '+9876543230',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        // Section 3 (Class 9A) - Students 11-15
        {
            userId: 17,
            admissionNumber: 'ADM011',
            rollNumber: '1',
            sectionId: 3,
            dateOfBirth: '2009-01-20',
            gender: 'Male',
            bloodGroup: 'O+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student011',
            password: 'student123',
            studentMobileNumber: '+9876543231',
            parentName: 'Mr. Karan Malhotra',
            parentMobileNumber: '+9876543232',
            feesConcession: 20,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 18,
            admissionNumber: 'ADM012',
            rollNumber: '2',
            sectionId: 3,
            dateOfBirth: '2009-03-28',
            gender: 'Female',
            bloodGroup: 'AB+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student012',
            password: 'student123',
            studentMobileNumber: '+9876543233',
            parentName: 'Mrs. Anjali Kapoor',
            parentMobileNumber: '+9876543234',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 19,
            admissionNumber: 'ADM013',
            rollNumber: '3',
            sectionId: 3,
            dateOfBirth: '2009-05-16',
            gender: 'Male',
            bloodGroup: 'A+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student013',
            password: 'student123',
            studentMobileNumber: '+9876543235',
            parentName: 'Mr. Deepak Rao',
            parentMobileNumber: '+9876543236',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 20,
            admissionNumber: 'ADM014',
            rollNumber: '4',
            sectionId: 3,
            dateOfBirth: '2009-07-08',
            gender: 'Female',
            bloodGroup: 'B+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student014',
            password: 'student123',
            studentMobileNumber: '+9876543237',
            parentName: 'Mrs. Shalini Nair',
            parentMobileNumber: '+9876543238',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 21,
            admissionNumber: 'ADM015',
            rollNumber: '5',
            sectionId: 3,
            dateOfBirth: '2009-09-19',
            gender: 'Male',
            bloodGroup: 'O+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student015',
            password: 'student123',
            studentMobileNumber: '+9876543239',
            parentName: 'Mr. Arun Desai',
            parentMobileNumber: '+9876543240',
            feesConcession: 10,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        // Section 4 (Class 9B) - Students 16-20
        {
            userId: 22,
            admissionNumber: 'ADM016',
            rollNumber: '1',
            sectionId: 4,
            dateOfBirth: '2009-02-11',
            gender: 'Female',
            bloodGroup: 'AB+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student016',
            password: 'student123',
            studentMobileNumber: '+9876543241',
            parentName: 'Mrs. Rekha Iyer',
            parentMobileNumber: '+9876543242',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 23,
            admissionNumber: 'ADM017',
            rollNumber: '2',
            sectionId: 4,
            dateOfBirth: '2009-04-25',
            gender: 'Male',
            bloodGroup: 'A+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student017',
            password: 'student123',
            studentMobileNumber: '+9876543243',
            parentName: 'Mr. Manoj Bhatt',
            parentMobileNumber: '+9876543244',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 24,
            admissionNumber: 'ADM018',
            rollNumber: '3',
            sectionId: 4,
            dateOfBirth: '2009-06-17',
            gender: 'Female',
            bloodGroup: 'B+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student018',
            password: 'student123',
            studentMobileNumber: '+9876543245',
            parentName: 'Mrs. Meera Pillai',
            parentMobileNumber: '+9876543246',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 25,
            admissionNumber: 'ADM019',
            rollNumber: '4',
            sectionId: 4,
            dateOfBirth: '2009-08-29',
            gender: 'Male',
            bloodGroup: 'O+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student019',
            password: 'student123',
            studentMobileNumber: '+9876543247',
            parentName: 'Mr. Sandeep Mishra',
            parentMobileNumber: '+9876543248',
            feesConcession: 5,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 26,
            admissionNumber: 'ADM020',
            rollNumber: '5',
            sectionId: 4,
            dateOfBirth: '2009-10-13',
            gender: 'Female',
            bloodGroup: 'AB+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student020',
            password: 'student123',
            studentMobileNumber: '+9876543249',
            parentName: 'Mrs. Divya Saxena',
            parentMobileNumber: '+9876543250',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        // Section 5 (Class 10A) - Students 21-25
        {
            userId: 27,
            admissionNumber: 'ADM021',
            rollNumber: '1',
            sectionId: 5,
            dateOfBirth: '2008-03-10',
            gender: 'Male',
            bloodGroup: 'A+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student021',
            password: 'student123',
            studentMobileNumber: '+9876543251',
            parentName: 'Mr. Ashok Pandey',
            parentMobileNumber: '+9876543252',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 28,
            admissionNumber: 'ADM022',
            rollNumber: '2',
            sectionId: 5,
            dateOfBirth: '2008-05-24',
            gender: 'Female',
            bloodGroup: 'B+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student022',
            password: 'student123',
            studentMobileNumber: '+9876543253',
            parentName: 'Mrs. Lata Chawla',
            parentMobileNumber: '+9876543254',
            feesConcession: 15,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 29,
            admissionNumber: 'ADM023',
            rollNumber: '3',
            sectionId: 5,
            dateOfBirth: '2008-07-15',
            gender: 'Male',
            bloodGroup: 'O+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student023',
            password: 'student123',
            studentMobileNumber: '+9876543255',
            parentName: 'Mr. Vinod Kulkarni',
            parentMobileNumber: '+9876543256',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 30,
            admissionNumber: 'ADM024',
            rollNumber: '4',
            sectionId: 5,
            dateOfBirth: '2008-09-07',
            gender: 'Female',
            bloodGroup: 'AB+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student024',
            password: 'student123',
            studentMobileNumber: '+9876543257',
            parentName: 'Mrs. Shweta Dutta',
            parentMobileNumber: '+9876543258',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 31,
            admissionNumber: 'ADM025',
            rollNumber: '5',
            sectionId: 5,
            dateOfBirth: '2008-11-21',
            gender: 'Male',
            bloodGroup: 'A+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student025',
            password: 'student123',
            studentMobileNumber: '+9876543259',
            parentName: 'Mr. Harish Bose',
            parentMobileNumber: '+9876543260',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        // Section 6 (Class 10B) - Students 26-30
        {
            userId: 32,
            admissionNumber: 'ADM026',
            rollNumber: '1',
            sectionId: 6,
            dateOfBirth: '2008-02-14',
            gender: 'Female',
            bloodGroup: 'B+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student026',
            password: 'student123',
            studentMobileNumber: '+9876543261',
            parentName: 'Mrs. Geeta Sinha',
            parentMobileNumber: '+9876543262',
            feesConcession: 10,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 33,
            admissionNumber: 'ADM027',
            rollNumber: '2',
            sectionId: 6,
            dateOfBirth: '2008-04-19',
            gender: 'Male',
            bloodGroup: 'O+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student027',
            password: 'student123',
            studentMobileNumber: '+9876543263',
            parentName: 'Mr. Nitin Thakur',
            parentMobileNumber: '+9876543264',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 34,
            admissionNumber: 'ADM028',
            rollNumber: '3',
            sectionId: 6,
            dateOfBirth: '2008-06-26',
            gender: 'Female',
            bloodGroup: 'AB+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student028',
            password: 'student123',
            studentMobileNumber: '+9876543265',
            parentName: 'Mrs. Ritu Bansal',
            parentMobileNumber: '+9876543266',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 35,
            admissionNumber: 'ADM029',
            rollNumber: '4',
            sectionId: 6,
            dateOfBirth: '2008-08-12',
            gender: 'Male',
            bloodGroup: 'A+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student029',
            password: 'student123',
            studentMobileNumber: '+9876543267',
            parentName: 'Mr. Ravi Ghosh',
            parentMobileNumber: '+9876543268',
            feesConcession: 0,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
        {
            userId: 36,
            admissionNumber: 'ADM030',
            rollNumber: '5',
            sectionId: 6,
            dateOfBirth: '2008-10-30',
            gender: 'Female',
            bloodGroup: 'B+',
            address: '123 Main Street, City, State',
            emergencyContact: '+9876543210',
            username: 'student030',
            password: 'student123',
            studentMobileNumber: '+9876543269',
            parentName: 'Mrs. Sapna Chopra',
            parentMobileNumber: '+9876543270',
            feesConcession: 5,
            isIrregular: false,
            remarksColor: 'green',
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(students).values(sampleStudents);
    
    console.log('✅ Students seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});