import { db } from '@/db';
import { users } from '@/db/schema';
import bcrypt from 'bcrypt';

async function main() {
    const timestamp = new Date().toISOString();
    
    // Hash passwords
    const adminPassword = await bcrypt.hash('admin123', 10);
    const teacherPassword = await bcrypt.hash('teacher123', 10);
    const studentPassword = await bcrypt.hash('student123', 10);
    const parentPassword = await bcrypt.hash('parent123', 10);
    
    const sampleUsers = [
        // Admin User (ID: 1)
        {
            email: 'admin@school.com',
            passwordHash: adminPassword,
            role: 'admin',
            fullName: 'Admin User',
            phone: '+1234567890',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        
        // Teacher Users (IDs: 2-6)
        {
            email: 'teacher1@school.com',
            passwordHash: teacherPassword,
            role: 'teacher',
            fullName: 'John Smith',
            phone: '+1234567891',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'teacher2@school.com',
            passwordHash: teacherPassword,
            role: 'teacher',
            fullName: 'Emily Johnson',
            phone: '+1234567892',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'teacher3@school.com',
            passwordHash: teacherPassword,
            role: 'teacher',
            fullName: 'Michael Brown',
            phone: '+1234567893',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'teacher4@school.com',
            passwordHash: teacherPassword,
            role: 'teacher',
            fullName: 'Sarah Davis',
            phone: '+1234567894',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'teacher5@school.com',
            passwordHash: teacherPassword,
            role: 'teacher',
            fullName: 'David Wilson',
            phone: '+1234567895',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        
        // Student Users (IDs: 7-36)
        {
            email: 'student1@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 1',
            phone: '+1234567900',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student2@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 2',
            phone: '+1234567901',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student3@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 3',
            phone: '+1234567902',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student4@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 4',
            phone: '+1234567903',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student5@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 5',
            phone: '+1234567904',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student6@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 6',
            phone: '+1234567905',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student7@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 7',
            phone: '+1234567906',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student8@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 8',
            phone: '+1234567907',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student9@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 9',
            phone: '+1234567908',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student10@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 10',
            phone: '+1234567909',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student11@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 11',
            phone: '+1234567910',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student12@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 12',
            phone: '+1234567911',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student13@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 13',
            phone: '+1234567912',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student14@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 14',
            phone: '+1234567913',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student15@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 15',
            phone: '+1234567914',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student16@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 16',
            phone: '+1234567915',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student17@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 17',
            phone: '+1234567916',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student18@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 18',
            phone: '+1234567917',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student19@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 19',
            phone: '+1234567918',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student20@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 20',
            phone: '+1234567919',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student21@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 21',
            phone: '+1234567920',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student22@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 22',
            phone: '+1234567921',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student23@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 23',
            phone: '+1234567922',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student24@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 24',
            phone: '+1234567923',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student25@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 25',
            phone: '+1234567924',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student26@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 26',
            phone: '+1234567925',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student27@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 27',
            phone: '+1234567926',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student28@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 28',
            phone: '+1234567927',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student29@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 29',
            phone: '+1234567928',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'student30@school.com',
            passwordHash: studentPassword,
            role: 'student',
            fullName: 'Student 30',
            phone: '+1234567929',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        
        // Parent Users (IDs: 37-51)
        {
            email: 'parent1@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 1',
            phone: '+1234567930',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent2@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 2',
            phone: '+1234567931',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent3@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 3',
            phone: '+1234567932',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent4@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 4',
            phone: '+1234567933',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent5@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 5',
            phone: '+1234567934',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent6@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 6',
            phone: '+1234567935',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent7@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 7',
            phone: '+1234567936',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent8@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 8',
            phone: '+1234567937',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent9@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 9',
            phone: '+1234567938',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent10@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 10',
            phone: '+1234567939',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent11@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 11',
            phone: '+1234567940',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent12@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 12',
            phone: '+1234567941',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent13@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 13',
            phone: '+1234567942',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent14@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 14',
            phone: '+1234567943',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
        {
            email: 'parent15@school.com',
            passwordHash: parentPassword,
            role: 'parent',
            fullName: 'Parent 15',
            phone: '+1234567944',
            isActive: true,
            createdAt: timestamp,
            updatedAt: timestamp,
        },
    ];

    await db.insert(users).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully');
    console.log(`   - 1 Admin user created`);
    console.log(`   - 5 Teacher users created`);
    console.log(`   - 30 Student users created`);
    console.log(`   - 15 Parent users created`);
    console.log(`   Total: 51 users`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});